# Generated by Django 5.1.4 on 2025-04-25 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolDetails_Manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='category',
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('grade_level', models.IntegerField()),
                ('day', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('time_interval', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolDetails_Manager.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=20)),
                ('content', models.JSONField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolDetails_Manager.section')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='SchoolDetails_Manager.timetable')),
            ],
        ),
    ]
