# Generated by Django 5.2 on 2025-04-25 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolDetails_Manager', '0002_remove_teacher_category_timetable_timetablecell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='adviser',
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day_of_week', models.CharField(max_length=10)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolDetails_Manager.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='Advisorship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolDetails_Manager.schoolyear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisorships', to='SchoolDetails_Manager.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisorships', to='SchoolDetails_Manager.teacher')),
            ],
            options={
                'unique_together': {('section', 'school_year', 'is_active')},
            },
        ),
    ]
