# Generated by Django 5.2 on 2025-04-25 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolDetails_Manager', '0003_remove_section_adviser_timeslot_advisorship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='school_year',
        ),
        migrations.AlterField(
            model_name='subject',
            name='school_year',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school_year',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='section',
            name='school_year',
            field=models.CharField(max_length=9),
        ),
        migrations.RemoveField(
            model_name='timetablecell',
            name='timetable',
        ),
        migrations.RemoveField(
            model_name='timetablecell',
            name='section',
        ),
        migrations.AddField(
            model_name='section',
            name='adviser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_sections', to='SchoolDetails_Manager.teacher'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school_year', models.CharField(max_length=9)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='SchoolDetails_Manager.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='SchoolDetails_Manager.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='SchoolDetails_Manager.teacher')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='SchoolDetails_Manager.timeslot')),
            ],
            options={
                'unique_together': {('section', 'timeslot', 'school_year')},
            },
        ),
        migrations.DeleteModel(
            name='Advisorship',
        ),
        migrations.DeleteModel(
            name='SchoolYear',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
        migrations.DeleteModel(
            name='TimetableCell',
        ),
    ]
