# Generated by Django 5.2 on 2025-04-25 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolDetails_Manager', '0004_remove_timeslot_school_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('year_range', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='category',
            field=models.CharField(default='Regular', max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='adviser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SchoolDetails_Manager.teacher'),
        ),
        migrations.AlterField(
            model_name='section',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolDetails_Manager.schoolyear'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolDetails_Manager.schoolyear'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolDetails_Manager.schoolyear'),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('grade_level', models.IntegerField()),
                ('day', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('time_interval', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolDetails_Manager.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=20)),
                ('content', models.JSONField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolDetails_Manager.section')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='SchoolDetails_Manager.timetable')),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
