# Generated by Django 5.1.4 on 2025-04-25 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolDetails_Manager', '0005_schoolyear_teacher_category_alter_section_adviser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='category',
        ),
    ]
