# Generated by Django 5.1.4 on 2025-04-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolDetails_Manager', '0006_remove_teacher_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='category',
            field=models.CharField(default='Regular', max_length=50),
        ),
    ]
