# Generated by Django 5.1.4 on 2025-04-27 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolDetails_Manager', '0002_remove_teacher_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='school_year',
        ),
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolDetails_Manager.schoolyear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolDetails_Manager.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolDetails_Manager.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'section', 'school_year')},
            },
        ),
    ]
