# Generated by Django 5.2 on 2025-04-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolDetails_Manager', '0005_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='school_year',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='advisory',
            name='school_year',
            field=models.CharField(max_length=9),
        ),
        migrations.DeleteModel(
            name='SchoolYear',
        ),
    ]
