# Generated by Django 5.2 on 2025-04-29 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolDetails_Manager', '0006_alter_schedule_school_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='adviser',
        ),
    ]
