# Generated by Django 5.2 on 2025-04-29 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolDetails_Manager', '0007_remove_section_adviser'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='advisory',
            unique_together={('section', 'school_year')},
        ),
        migrations.AlterField(
            model_name='advisory',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolDetails_Manager.teacher'),
        ),
    ]
