# Generated by Django 5.2 on 2025-05-16 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolDetails_Manager', '0008_alter_advisory_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='grade_level',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
    ]
